name: "构建JD正式版"
on:
  workflow_dispatch:

jobs:
  build:
    name: 构建JD正式版
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 设置QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 设置Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      
      - name: Docker buildx image and push arm64
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/arm64 --tag registry.cn-hangzhou.aliyuncs.com/djxiao71/jd777:arm65 docker/
          
      - name: Docker buildx image and push amd64
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/amd64 --tag registry.cn-hangzhou.aliyuncs.com/djxiao71/jd777:amd65 docker/
