name: Publish Docker Image
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username="${DOCKER_USERNAME}" registry.cn-hangzhou.aliyuncs.com --password-stdin
      
      - name: Docker buildx image and push arm64
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/arm64 --tag registry.cn-hangzhou.aliyuncs.com/djxiao71/jd777:arm64 docker/
          
      - name: Docker buildx image and push arm
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/arm/v7 --tag registry.cn-hangzhou.aliyuncs.com/djxiao71/jd777:arm docker/
          
      - name: Docker buildx image and push amd64
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/amd64 --tag registry.cn-hangzhou.aliyuncs.com/djxiao71/jd777:amd64 docker/
